remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

gem "github-pages", group: :jekyll_plugins

title: Towards FAIR4ML - A tutorial at KI2025
description: A practical approach to documentation and metadata good practices for machine learning models - FAIR4ML2025

show_downloads: false
